// ── uiStrings.js ──────────────────────────────────────────────────────────
// Flat English → Hindi dictionary used by the tr() helper (see
// LanguageContext.jsx) across every page except HomePage (which uses the
// structured `translations.js` object instead).
//
// Usage in a page component:
//   const { tr } = useLanguage();
//   <h1>{tr("Book a Lawyer")}</h1>
//
// Add new keys here whenever new visible English text is added to any page.

export const uiStrings = {
  "← Back to Home Page": "← होमपेज पर वापस जाएँ",

  // BookLawyerPage.jsx
  "Book a Lawyer": "वकील बुक करें",
  "When does your case need a lawyer —": "आपके केस को वकील की ज़रूरत कब है —",
  "now, or already underway?": "अभी, या केस पहले से चल रहा है?",
  "Pick the path that matches where you are. Both connect you to a verified criminal lawyer — the only difference is where in the case they step in.":
    "अपनी स्थिति के अनुसार रास्ता चुनें। दोनों रास्ते आपको एक सत्यापित आपराधिक वकील से जोड़ते हैं — फ़र्क़ सिर्फ़ इतना है कि वे केस में कब जुड़ते हैं।",
  Flagship: "फ्लैगशिप",
  "Lawyer from Day 1 of the Case": "केस के पहले दिन से वकील",
  "File your report and get a lawyer assigned the same day — before evidence goes cold and while every detail is still fresh.":
    "अपनी रिपोर्ट फाइल करें और उसी दिन वकील पाएं — सबूत ठंडे पड़ने से पहले और जब हर विवरण अभी भी ताज़ा हो।",
  "Start this path": "यह रास्ता शुरू करें",
  "Mid-Case": "केस के बीच में",
  "Lawyer in Between the Case": "केस के बीच में वकील",
  "Already have an ongoing case — with or without a lawyer — and need someone to step in now? Get matched based on where things currently stand.":
    "क्या आपका केस पहले से चल रहा है — वकील के साथ या बिना — और अभी किसी की ज़रूरत है? मौजूदा स्थिति के आधार पर मिलान पाएं।",

  // BookLawyerDay1Page.jsx
  "Lawyer · Day 1": "वकील · दिन 1",
  "Get a lawyer assigned": "वकील नियुक्त कराएं",
  "the same day you report.": "जिस दिन आप रिपोर्ट करें, उसी दिन।",
  "Tell us the basics and a criminal defence lawyer from our Day-1 response team is matched to your case immediately.":
    "हमें बुनियादी जानकारी बताएं और हमारी डे-1 रिस्पॉन्स टीम का एक आपराधिक बचाव वकील तुरंत आपके केस से जोड़ा जाएगा।",
  Email: "ईमेल",
  "you@example.com": "you@example.com",
  "Phone Number": "फ़ोन नंबर",
  "How can we reach you?": "हम आपसे कैसे संपर्क करें?",
  Address: "पता",
  "Your current address": "आपका वर्तमान पता",
  "Location of Crime": "अपराध का स्थान",
  "Where did it happen?": "यह कहाँ हुआ?",
  "FIR Number (if already filed)": "एफआईआर नंबर (यदि पहले से दर्ज है)",
  "e.g. FIR-2026-00231": "उदा. FIR-2026-00231",
  "Case Document": "केस दस्तावेज़",
  "Briefly Describe the Case": "केस का संक्षेप में विवरण दें",
  "What happened, and when?": "क्या हुआ, और कब?",
  "Assign a Lawyer Now": "अभी वकील नियुक्त करें",
  "Confidential. Free, demo booking flow — no charges, no obligation.":
    "गोपनीय। मुफ़्त, डेमो बुकिंग फ्लो — कोई शुल्क नहीं, कोई बाध्यता नहीं।",
  "Fill the form — your assigned lawyer and booking ID will appear here right away.":
    "फ़ॉर्म भरें — आपका नियुक्त वकील और बुकिंग आईडी यहाँ तुरंत दिखाई देगी।",
  "Lawyer Assigned": "वकील नियुक्त",
  "They'll reach out within approximately": "वे लगभग इस समय में संपर्क करेंगे",
  "hour(s)": "घंटे में",
  "to begin building your defence while the case is still fresh.":
    "ताकि केस अभी ताज़ा रहते हुए आपका बचाव तैयार करना शुरू किया जा सके।",
  "Booking Details": "बुकिंग विवरण",
  "Booking ID": "बुकिंग आईडी",
  "Demo flow — not yet connected to a live lawyer network.":
    "डेमो फ्लो — अभी तक किसी लाइव वकील नेटवर्क से जुड़ा नहीं है।",

  // BookLawyerInBetweenPage.jsx
  "Lawyer · In Between the Case": "वकील · केस के बीच में",
  "Bring in a lawyer": "वकील लाएं",
  "wherever your case currently stands.": "आपका केस चाहे किसी भी स्थिति में हो।",
  "Whether you're mid-investigation, awaiting a hearing, or switching representation, tell us the current stage and we'll match someone who can step in without losing time.":
    "चाहे आप जांच के बीच में हों, सुनवाई का इंतज़ार कर रहे हों, या वकील बदल रहे हों — हमें मौजूदा चरण बताएं और हम बिना समय गंवाए किसी को आपसे जोड़ देंगे।",
  "Current Stage of the Case": "केस का मौजूदा चरण",
  "Select the current stage": "मौजूदा चरण चुनें",
  "Under Police Investigation": "पुलिस जांच के अधीन",
  "Chargesheet Filed": "चार्जशीट दाखिल",
  "Trial in Progress": "मुकदमा चल रहा है",
  "Switching from Current Lawyer": "मौजूदा वकील बदल रहे हैं",
  "What's the case about, and where does it stand?": "केस किस बारे में है, और यह किस स्थिति में है?",
  "Find a Lawyer for My Stage": "मेरे चरण के लिए वकील खोजें",
  "Fill the form — your matched lawyer and booking ID will appear here right away.":
    "फ़ॉर्म भरें — आपका मिलान किया गया वकील और बुकिंग आईडी यहाँ तुरंत दिखाई देगी।",
  "Lawyer Matched": "वकील मिलान हुआ",
  "They'll review your case stage and reach out within approximately": "वे आपके केस के चरण की समीक्षा करेंगे और लगभग इस समय में संपर्क करेंगे",
  hours: "घंटों में",
  "to discuss next steps.": "अगले कदमों पर चर्चा करने के लिए।",

  // CaseStatusPage.jsx — GOVT_LINKS
  "eCourts Services": "ई-कोर्ट्स सेवाएँ",
  "Official case status, cause lists & orders for district/high courts.":
    "ज़िला/हाई कोर्ट के लिए आधिकारिक केस स्थिति, कॉज़ लिस्ट और आदेश।",
  "National Judicial Data Grid (NJDG)": "नेशनल ज्यूडिशियल डेटा ग्रिड (NJDG)",
  "Live pendency & disposal data for courts across India.":
    "भारत भर की अदालतों के लिए लाइव लंबित व निपटान डेटा।",
  "NALSA — Free Legal Aid": "नालसा — मुफ़्त कानूनी सहायता",
  "Apply for free legal aid under the Legal Services Authorities Act.":
    "विधिक सेवा प्राधिकरण अधिनियम के तहत मुफ़्त कानूनी सहायता के लिए आवेदन करें।",
  "Digital Police Portal": "डिजिटल पुलिस पोर्टल",
  "NCRB / MHA portal for FIR status, verification & citizen services.":
    "एफआईआर स्थिति, सत्यापन और नागरिक सेवाओं के लिए NCRB / MHA पोर्टल।",
  "India Code": "इंडिया कोड",
  "Official digital repository of all Central & State Acts.":
    "सभी केंद्रीय और राज्य अधिनियमों का आधिकारिक डिजिटल भंडार।",
  "National Cyber Crime Reporting Portal": "राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल",
  "Report cybercrime directly to the Ministry of Home Affairs (I4C).":
    "गृह मंत्रालय (I4C) को सीधे साइबर अपराध की रिपोर्ट करें।",
  "Free · No charges": "मुफ़्त · कोई शुल्क नहीं",

  // CaseStatusPage.jsx — stages
  "FIR Filed": "एफआईआर दर्ज",
  Investigation: "जांच",
  Chargesheet: "चार्जशीट",
  Trial: "मुकदमा",
  Judgment: "फैसला",

  // CaseStatusPage.jsx — validation
  "Please enter your name.": "कृपया अपना नाम दर्ज करें।",
  "Please enter your email.": "कृपया अपना ईमेल दर्ज करें।",
  "Please enter a valid email.": "कृपया एक मान्य ईमेल दर्ज करें।",
  "Please enter your phone number.": "कृपया अपना फ़ोन नंबर दर्ज करें।",
  "Please enter your address.": "कृपया अपना पता दर्ज करें।",
  "Please enter the location of the crime.": "कृपया अपराध का स्थान दर्ज करें।",
  "Please enter your case / FIR number.": "कृपया अपना केस / एफआईआर नंबर दर्ज करें।",
  "Please select a case type.": "कृपया केस का प्रकार चुनें।",

  // CaseStatusPage.jsx — page copy
  "Case Information": "केस जानकारी",
  "Track your": "अपने",
  "case status.": "केस की स्थिति ट्रैक करें।",
  "Enter your details and case number to see how far your case has progressed and your next hearing date.":
    "आपका केस कितना आगे बढ़ा है और आपकी अगली सुनवाई की तारीख देखने के लिए अपनी जानकारी और केस नंबर दर्ज करें।",
  "This is a demo tracker, not a live court database.": "यह एक डेमो ट्रैकर है, लाइव कोर्ट डेटाबेस नहीं।",
  "It is not connected to eCourts or any police/judicial system, so the result shown below is illustrative only. What you enter is sent to our team over WhatsApp so we can follow up, but no real case data is fetched from any court. For your actual case status, use the official":
    "यह ई-कोर्ट्स या किसी भी पुलिस/न्यायिक सिस्टम से जुड़ा नहीं है, इसलिए नीचे दिखाया गया परिणाम केवल उदाहरण के लिए है। आपके द्वारा दर्ज की गई जानकारी हमारी टीम को व्हाट्सएप पर भेजी जाती है ताकि हम फॉलो-अप कर सकें, लेकिन किसी भी अदालत से असली केस डेटा प्राप्त नहीं किया जाता। अपनी वास्तविक केस स्थिति के लिए, आधिकारिक",
  "eCourts India — Case Status": "ई-कोर्ट्स इंडिया — केस स्थिति",
  "page.": "पेज का उपयोग करें।",
  "Track your real case on the official eCourts portal": "आधिकारिक ई-कोर्ट्स पोर्टल पर अपना असली केस ट्रैक करें",
  "Free · Govt. of India · Opens in a new tab": "मुफ़्त · भारत सरकार · नए टैब में खुलता है",
  "or try the illustrative demo below": "या नीचे उदाहरण डेमो आज़माएं",
  "Your Name": "आपका नाम",
  "Full name": "पूरा नाम",
  "Your phone number": "आपका फ़ोन नंबर",
  "Case / FIR Number": "केस / एफआईआर नंबर",
  "Case Document (optional)": "केस दस्तावेज़ (वैकल्पिक)",
  "Type of Case": "केस का प्रकार",
  "Select a case type": "केस का प्रकार चुनें",
  "Cybercrime / Online Fraud": "साइबर अपराध / ऑनलाइन धोखाधड़ी",
  "Theft / Burglary": "चोरी / सेंधमारी",
  "Assault / Physical Violence": "हमला / शारीरिक हिंसा",
  "Domestic Violence": "घरेलू हिंसा",
  "Missing Person / Child": "लापता व्यक्ति / बच्चा",
  "Harassment / Cyberbullying": "उत्पीड़न / साइबरबुलिंग",
  "Financial Fraud / Cheating": "वित्तीय धोखाधड़ी / ठगी",
  "Drug-Related Crime": "नशीली दवाओं से जुड़ा अपराध",
  Other: "अन्य",
  "City / Court (optional)": "शहर / अदालत (वैकल्पिक)",
  "e.g. Ludhiana District Court": "उदा. लुधियाना ज़िला अदालत",
  "Find this court on eCourts": "ई-कोर्ट्स पर यह अदालत खोजें",
  "Check Case Status": "केस की स्थिति जांचें",
  "Free to use. No penalty or fee involved.": "उपयोग करना मुफ़्त है। कोई जुर्माना या शुल्क नहीं।",
  "Demo Result — Not Live Court Data": "डेमो परिणाम — लाइव कोर्ट डेटा नहीं",
  "This is a": "यह एक",
  "simulated demo result": "सिम्युलेटेड डेमो परिणाम है",
  "generated only from the case number you typed. It is": "जो केवल आपके द्वारा दर्ज किए गए केस नंबर से बनाया गया है। यह",
  "not fetched from eCourts or any real court/police database": "ई-कोर्ट्स या किसी भी वास्तविक अदालत/पुलिस डेटाबेस से प्राप्त नहीं किया गया है",
  "and must not be used to plan your actual hearing date. For your real case status, visit the official":
    "और इसका उपयोग आपकी वास्तविक सुनवाई की तारीख की योजना बनाने के लिए नहीं किया जाना चाहिए। अपनी असली केस स्थिति के लिए, आधिकारिक",
  "Case Status": "केस की स्थिति",
  for: "के लिए",
  Progress: "प्रगति",
  "Current Stage": "मौजूदा चरण",
  "Next Hearing Date": "अगली सुनवाई की तारीख",
  "Case Type": "केस का प्रकार",
  "City / Court": "शहर / अदालत",
  "Not specified": "निर्दिष्ट नहीं",
  "Track on Official eCourts Portal": "आधिकारिक ई-कोर्ट्स पोर्टल पर ट्रैक करें",
  "Check Another Case": "दूसरा केस जांचें",
  "Back to Home": "होम पर वापस जाएं",
  "Official Government Resources": "आधिकारिक सरकारी संसाधन",
  "Verified links, straight from the source": "स्रोत से सीधे, सत्यापित लिंक",
  "Every link below points to an official Government of India (.gov.in / .nic.in) portal. Nothing is proxied, embedded, or tracked — each opens directly in a new tab.":
    "नीचे दिया गया हर लिंक एक आधिकारिक भारत सरकार (.gov.in / .nic.in) पोर्टल की ओर इशारा करता है। कुछ भी प्रॉक्सी, एम्बेड या ट्रैक नहीं किया जाता — प्रत्येक सीधे नए टैब में खुलता है।",

  // ForensicExpertPage.jsx
  "Forensic Services": "फॉरेंसिक सेवाएँ",
  "Evidence fades fast —": "सबूत तेज़ी से मिटते हैं —",
  "secure it before it does.": "इससे पहले कि वे मिटें, उन्हें सुरक्षित करें।",
  "Certified forensic experts document and preserve digital and physical evidence so it holds up in court, however long the case takes to conclude.":
    "प्रमाणित फॉरेंसिक विशेषज्ञ डिजिटल और भौतिक सबूतों का दस्तावेज़ीकरण और संरक्षण करते हैं ताकि केस चाहे जितना लंबा चले, वे अदालत में टिके रहें।",
  Secure: "सुरक्षित करें",
  "Evidence is collected and sealed before it degrades or gets tampered with.":
    "सबूत के खराब होने या छेड़छाड़ होने से पहले उसे एकत्र और सील किया जाता है।",
  Analyze: "विश्लेषण करें",
  "Certified examiners document chain of custody and findings.":
    "प्रमाणित परीक्षक चेन ऑफ कस्टडी और निष्कर्षों का दस्तावेज़ीकरण करते हैं।",
  "Court-Ready Report": "कोर्ट के लिए तैयार रिपोर्ट",
  "A formal report your lawyer can submit directly as evidence.":
    "एक औपचारिक रिपोर्ट जिसे आपका वकील सीधे सबूत के रूप में प्रस्तुत कर सकता है।",
  "Type of Evidence": "सबूत का प्रकार",
  "Select what needs to be examined": "चुनें कि क्या जांचा जाना है",
  "Digital (phone, laptop, accounts)": "डिजिटल (फ़ोन, लैपटॉप, अकाउंट)",
  "Physical (objects, documents, scene)": "भौतिक (वस्तुएं, दस्तावेज़, घटनास्थल)",
  "Medical / Biological": "चिकित्सा / जैविक",
  "FIR Number (if any)": "एफआईआर नंबर (यदि है)",
  "What Needs to Be Preserved?": "क्या संरक्षित किया जाना चाहिए?",
  "Briefly describe the evidence and where it currently is":
    "सबूत और वह वर्तमान में कहाँ है, इसका संक्षेप में विवरण दें",
  "Book a Forensic Expert": "फॉरेंसिक विशेषज्ञ बुक करें",
  "Fill the form — your matched forensic expert and booking ID will appear here right away.":
    "फ़ॉर्म भरें — आपका मिलान किया गया फॉरेंसिक विशेषज्ञ और बुकिंग आईडी यहाँ तुरंत दिखाई देगी।",
  "Expert Matched": "विशेषज्ञ मिलान हुआ",
  "to begin securing and documenting the evidence.": "सबूत को सुरक्षित करने और दस्तावेज़ीकरण शुरू करने के लिए।",
  "Demo flow — not yet connected to a live forensic network.":
    "डेमो फ्लो — अभी तक किसी लाइव फॉरेंसिक नेटवर्क से जुड़ा नहीं है।",

  // LegalDraftingPage.jsx
  "Legal & Corporate Drafting": "कानूनी और कॉर्पोरेट ड्राफ्टिंग",
  "Notices, contracts, policies —": "नोटिस, अनुबंध, नीतियां —",
  "drafted right, drafted fast.": "सही ढंग से, तेज़ी से तैयार।",
  "Get legal notices, agreements, compliance reports, and corporate policy documents drafted by a qualified legal professional, ready for review or filing.":
    "एक योग्य कानूनी पेशेवर से कानूनी नोटिस, अनुबंध, अनुपालन रिपोर्ट और कॉर्पोरेट नीति दस्तावेज़ तैयार करवाएं, जो समीक्षा या फाइलिंग के लिए तैयार हों।",
  Brief: "जानकारी दें",
  "Tell us the document type and what it needs to cover.": "हमें दस्तावेज़ का प्रकार और उसमें क्या शामिल होना चाहिए, बताएं।",
  "Draft & Review": "ड्राफ्ट और समीक्षा",
  "A qualified drafter prepares the document and checks it against applicable law.":
    "एक योग्य ड्राफ्टर दस्तावेज़ तैयार करता है और लागू कानून के अनुसार उसकी जांच करता है।",
  "Ready to Use": "उपयोग के लिए तैयार",
  "Delivered in a format ready for signature, filing, or internal circulation.":
    "हस्ताक्षर, फाइलिंग, या आंतरिक प्रसार के लिए तैयार प्रारूप में दिया जाता है।",
  "Type of Document": "दस्तावेज़ का प्रकार",
  "Select what needs to be drafted": "चुनें कि क्या तैयार किया जाना है",
  "Legal Notice": "कानूनी नोटिस",
  "Contract / Agreement": "अनुबंध / समझौता",
  "Compliance Report": "अनुपालन रिपोर्ट",
  "Corporate Policy Document": "कॉर्पोरेट नीति दस्तावेज़",
  "Your Name / Organization": "आपका नाम / संगठन",
  "Full name or company name": "पूरा नाम या कंपनी का नाम",
  "Your current / registered address": "आपका वर्तमान / पंजीकृत पता",
  "Location of Crime / Incident (if applicable)": "अपराध / घटना का स्थान (यदि लागू हो)",
  "FIR Number (if applicable)": "एफआईआर नंबर (यदि लागू हो)",
  "What Should the Document Cover?": "दस्तावेज़ में क्या शामिल होना चाहिए?",
  "Key terms, parties involved, purpose, deadlines, etc.": "मुख्य शर्तें, शामिल पक्ष, उद्देश्य, समय-सीमा आदि।",
  "Request a Draft": "ड्राफ्ट का अनुरोध करें",
  "Fill the form — your matched drafter and booking ID will appear here right away.":
    "फ़ॉर्म भरें — आपका मिलान किया गया ड्राफ्टर और बुकिंग आईडी यहाँ तुरंत दिखाई देगी।",
  "Drafter Matched": "ड्राफ्टर मिलान हुआ",
  "Your document will be ready within approximately": "आपका दस्तावेज़ लगभग इस समय में तैयार हो जाएगा",
  "for your review before it's finalized.": "अंतिम रूप देने से पहले आपकी समीक्षा के लिए।",
  "Demo flow — not yet connected to a live drafting network.":
    "डेमो फ्लो — अभी तक किसी लाइव ड्राफ्टिंग नेटवर्क से जुड़ा नहीं है।",

  // NyayShieldPage.jsx (legacy quick-actions page)
  "We are here to support you": "हम आपकी मदद के लिए यहां हैं",
  "Pick one — each takes you straight to the right place, no digging through menus.":
    "एक चुनें — हर विकल्प आपको सीधे सही जगह ले जाता है, मेनू में खोजने की ज़रूरत नहीं।",
  "Report a Crime": "अपराध की रिपोर्ट करें",
  "File details, get routed instantly": "विवरण दर्ज करें, तुरंत सही जगह पहुंचें",
  "From Day 1, or later in the case": "पहले दिन से, या केस में बाद में",
  "Check Case Status": "केस की स्थिति जांचें",
  "Track progress & next hearing date": "प्रगति और अगली सुनवाई की तारीख ट्रैक करें",
  "Book a Forensic Expert": "फॉरेंसिक विशेषज्ञ बुक करें",
  "Secure evidence before it's gone": "सबूत खोने से पहले सुरक्षित करें",
  "Legal / Corporate Report Drafting": "कानूनी / कॉर्पोरेट रिपोर्ट ड्राफ्टिंग",
  "Notices, contracts & compliance docs": "नोटिस, अनुबंध और अनुपालन दस्तावेज़",

  // ReportCrimePage.jsx — hero
  "Not sure where to report?": "पता नहीं कहाँ रिपोर्ट करें?",
  "Report a Crime.": "अपराध की रिपोर्ट करें।",
  "Get to the": "सही प्राधिकरण तक",
  "right authority": "पहुंचें",
  ", fast.": ", तेज़ी से।",
  "Tell us what happened, and we'll match you with the correct official government portal — whether it's cyber crime, financial fraud, or a general police complaint.":
    "हमें बताएं क्या हुआ, और हम आपको सही आधिकारिक सरकारी पोर्टल से जोड़ देंगे — चाहे वह साइबर अपराध हो, वित्तीय धोखाधड़ी हो, या सामान्य पुलिस शिकायत।",
  "Register a Crime": "अपराध दर्ज करें",
  "Crime Categories Covered": "अपराध श्रेणियाँ शामिल",
  "Official Government Links": "आधिकारिक सरकारी लिंक",
  Min: "मिनट",
  "To Find the Right Portal": "सही पोर्टल खोजने में",

  // ReportCrimePage.jsx — form
  "Tell Us What Happened": "हमें बताएं क्या हुआ",
  "These details help us point you to the correct government authority. This form does not file a police report on your behalf.":
    "ये विवरण हमें आपको सही सरकारी प्राधिकरण तक पहुंचाने में मदद करते हैं। यह फॉर्म आपकी ओर से पुलिस रिपोर्ट दर्ज नहीं करता।",
  "Full Name": "पूरा नाम",
  "Your full name": "आपका पूरा नाम",
  "e.g. +91 98765 43210": "उदा. +91 98765 43210",
  "Email (optional)": "ईमेल (वैकल्पिक)",
  "Location of Incident": "घटना का स्थान",
  "City, State": "शहर, राज्य",
  "Type of Crime": "अपराध का प्रकार",
  "Select a category": "एक श्रेणी चुनें",
  "Date of Incident": "घटना की तारीख",
  "What Happened?": "क्या हुआ?",
  "Briefly describe the incident...": "घटना का संक्षेप में विवरण दें...",
  "Submit & Find Authorities": "जमा करें और प्राधिकरण खोजें",

  // ReportCrimePage.jsx — validation
  "Please enter a valid phone number.": "कृपया एक मान्य फ़ोन नंबर दर्ज करें।",
  "Please enter the location of the incident.": "कृपया घटना का स्थान दर्ज करें।",
  "Please select a crime type.": "कृपया अपराध का प्रकार चुनें।",
  "Please select the date of the incident.": "कृपया घटना की तारीख चुनें।",
  "Please describe what happened.": "कृपया बताएं क्या हुआ।",

  // ReportCrimePage.jsx — processing
  "Processing Your Report": "आपकी रिपोर्ट प्रोसेस हो रही है",
  "Reviewing the details you provided...": "आपके द्वारा दी गई जानकारी की समीक्षा हो रही है...",
  "Matching your case to the right authority...": "आपके केस को सही प्राधिकरण से मिलाया जा रहा है...",
  "Preparing your resource list...": "आपकी संसाधन सूची तैयार की जा रही है...",

  // ReportCrimePage.jsx — results
  "Thank You": "धन्यवाद",
  "Based on what you shared, this looks like a": "आपने जो साझा किया उसके आधार पर, यह एक",
  "case. We've highlighted the right authority below — you can also browse all categories.":
    "केस लगता है। हमने नीचे सही प्राधिकरण को हाइलाइट किया है — आप सभी श्रेणियां भी देख सकते हैं।",
  "Here are the official government authorities for every major crime category. Find the one that matches your situation.":
    "यहाँ हर प्रमुख अपराध श्रेणी के लिए आधिकारिक सरकारी प्राधिकरण हैं। अपनी स्थिति से मेल खाने वाला चुनें।",
  "This is not an FIR filing system.": "यह एक एफआईआर दाखिल करने की प्रणाली नहीं है।",
  "The details you shared were sent to our team over WhatsApp so we can follow up — but they are not filed with police or any court. This tool only helps you find the correct official portal. For urgent, life-threatening emergencies, call":
    "आपने जो विवरण साझा किए, वे हमारी टीम को व्हाट्सएप पर भेज दिए गए हैं ताकि हम फॉलो-अप कर सकें — लेकिन वे पुलिस या किसी अदालत में दर्ज नहीं किए गए हैं। यह टूल केवल आपको सही आधिकारिक पोर्टल खोजने में मदद करता है। तत्काल, जानलेवा आपात स्थिति के लिए, कॉल करें",
  "(India's national emergency number) immediately, or visit your nearest police station.":
    "(भारत का राष्ट्रीय आपातकालीन नंबर) तुरंत, या अपने नज़दीकी पुलिस स्टेशन पर जाएं।",
  Recommended: "अनुशंसित",
  "official resources": "आधिकारिक संसाधन",
  "official resource": "आधिकारिक संसाधन",
  "File Another Report": "एक और रिपोर्ट दर्ज करें",

  // ReportCrimePage.jsx — CATEGORIES (title / desc)
  "Cyber Crime": "साइबर अपराध",
  "Hacking, online fraud, phishing, identity theft, social media harassment, or any internet-based crime.":
    "हैकिंग, ऑनलाइन धोखाधड़ी, फ़िशिंग, पहचान की चोरी, सोशल मीडिया उत्पीड़न, या कोई भी इंटरनेट-आधारित अपराध।",
  "Women's Safety & Harassment": "महिला सुरक्षा और उत्पीड़न",
  "Harassment, domestic violence, stalking, or any crime against women.":
    "उत्पीड़न, घरेलू हिंसा, पीछा करना, या महिलाओं के खिलाफ कोई भी अपराध।",
  "Financial & Banking Fraud": "वित्तीय और बैंकिंग धोखाधड़ी",
  "Unauthorised transactions, loan scams, UPI fraud, or suspicious banking activity.":
    "अनधिकृत लेनदेन, ऋण घोटाले, यूपीआई धोखाधड़ी, या संदिग्ध बैंकिंग गतिविधि।",
  "Consumer Fraud": "उपभोक्ता धोखाधड़ी",
  "Fake products, defective goods, unfair trade practices, or e-commerce scams.":
    "नकली उत्पाद, दोषपूर्ण सामान, अनुचित व्यापार प्रथाएं, या ई-कॉमर्स घोटाले।",
  "Corporate & Financial Crime": "कॉर्पोरेट और वित्तीय अपराध",
  "Company fraud, embezzlement, or serious financial irregularities within an organisation.":
    "कंपनी धोखाधड़ी, गबन, या किसी संगठन के भीतर गंभीर वित्तीय अनियमितताएं।",
  "Tax Evasion": "कर चोरी",
  "Undisclosed income, GST fraud, or tax-related offences.":
    "अघोषित आय, जीएसटी धोखाधड़ी, या कर-संबंधी अपराध।",
  "General FIR / Local Crime": "सामान्य एफआईआर / स्थानीय अपराध",
  "Theft, assault, property crime, or anything that needs a First Information Report (FIR) — every state runs its own police portal.":
    "चोरी, हमला, संपत्ति अपराध, या कोई भी ऐसी चीज़ जिसके लिए प्रथम सूचना रिपोर्ट (एफआईआर) की आवश्यकता है — हर राज्य अपना पुलिस पोर्टल चलाता है।",
  "Missing Person / Child Safety": "लापता व्यक्ति / बाल सुरक्षा",
  "A missing person, missing child, or child-safety concern.":
    "एक लापता व्यक्ति, लापता बच्चा, या बाल-सुरक्षा संबंधी चिंता।",

  // ── Full-site Hindi coverage (About, Services, awareness pages, Home footer, navbar, misc) ──
  "Home": "होम",
  "About": "परिचय",
  "Services": "सेवाएँ",
  "Clients": "ग्राहक",
  "Programs": "कार्यक्रम",
  "Get in Touch": "संपर्क करें",
  "Our Approach": "हमारा दृष्टिकोण",
  "Quality Management": "गुणवत्ता प्रबंधन",
  "Information Security": "सूचना सुरक्षा",
  "Email Us": "हमें ईमेल करें",
  "© 2025 Forfra Solutions. ISO 9001:2015 & ISO 27001:2022 Certified.": "© 2025 Forfra Solutions. ISO 9001:2015 और ISO 27001:2022 प्रमाणित।",
  "Our": "हमारा",
  "DETECT. PROTECT. EVOLVE.": "पहचानें। सुरक्षित करें। विकसित हों।",
  "EVERY THREAT.": "हर खतरा।",
  "ONE PARTNER.": "एक साझेदार।",
  "Comprehensive forensic, security, and investigation solutions — court-ready, legally defensible, and backed by ISO-certified expertise.": "व्यापक फॉरेंसिक, सुरक्षा, और जांच समाधान — न्यायालय-तैयार, कानूनी रूप से सुरक्षित, और ISO-प्रमाणित विशेषज्ञता द्वारा समर्थित।",
  "DATA SECURITY": "डेटा सुरक्षा",
  "FORENSIC AUDIT": "फॉरेंसिक ऑडिट",
  "DIGITAL FORENSICS": "डिजिटल फॉरेंसिक्स",
  "FRAUD INVESTIGATION": "धोखाधड़ी जांच",
  "INVESTIGATIONS": "जांच",
  "LEGAL CONSULTATION": "कानूनी परामर्श",
  "DOCUMENT EXAMINATION": "दस्तावेज़ जांच",
  "CYBER INVESTIGATION": "साइबर जांच",
  "Scroll": "स्क्रॉल करें",
  "OUR SERVICES": "हमारी सेवाएँ",
  "ROYAL VAULT APPROACH": "रॉयल वॉल्ट दृष्टिकोण",
  "Data Security": "डेटा सुरक्षा",
  "Air-gapped systems, strong encryption, and strict access controls keep your data completely isolated, private, and tamper-proof.": "एयर-गैप्ड सिस्टम, मज़बूत एन्क्रिप्शन और सख्त एक्सेस नियंत्रण आपके डेटा को पूरी तरह से अलग, निजी और छेड़छाड़-रोधी बनाए रखते हैं।",
  "BEYOND TRADITIONAL AUDITS": "पारंपरिक ऑडिट से आगे",
  "Forensic Audit": "फॉरेंसिक ऑडिट",
  "Uncover fraud, financial irregularities, and hidden risks with investigative expertise and advanced analytics. Court-admissible reports guaranteed.": "जांच विशेषज्ञता और उन्नत विश्लेषण के साथ धोखाधड़ी, वित्तीय अनियमितताओं और छिपे जोखिमों को उजागर करें। न्यायालय-मान्य रिपोर्ट की गारंटी।",
  "END-TO-END INVESTIGATION": "एंड-टू-एंड जांच",
  "Digital Forensics": "डिजिटल फॉरेंसिक्स",
  "Data imaging, extraction, and in-depth analysis from mobile devices, computers, and networks with full chain of custody.": "मोबाइल डिवाइस, कंप्यूटर और नेटवर्क से डेटा इमेजिंग, निष्कर्षण और गहन विश्लेषण, पूर्ण चेन ऑफ कस्टडी के साथ।",
  "FOLLOW THE MONEY": "पैसे का पीछा करें",
  "Financial & Fraud Investigation": "वित्तीय और धोखाधड़ी जांच",
  "Uncover financial irregularities, trace complex transactions, and track fraud across banking systems — including cryptocurrency tracing.": "वित्तीय अनियमितताओं को उजागर करें, जटिल लेन-देन का पता लगाएं, और बैंकिंग सिस्टम में धोखाधड़ी को ट्रैक करें — क्रिप्टोकरेंसी ट्रेसिंग सहित।",
  "OSINT & DUE DILIGENCE": "OSINT और ड्यू डिलिजेंस",
  "Investigations & Intelligence": "जांच और इंटेलिजेंस",
  "Background verification, corporate & private investigations, OSINT, litigation support, and business risk assessment.": "पृष्ठभूमि सत्यापन, कॉर्पोरेट और निजी जांच, OSINT, मुकदमेबाज़ी सहायता, और व्यावसायिक जोखिम मूल्यांकन।",
  "FORENSIC-LEGAL BRIDGE": "फॉरेंसिक-कानूनी सेतु",
  "Legal Consultation": "कानूनी परामर्श",
  "Translating digital and physical evidence into legally admissible insights — bridging forensic science and courtroom strategy.": "डिजिटल और भौतिक सबूतों को कानूनी रूप से स्वीकार्य अंतर्दृष्टि में बदलना — फॉरेंसिक विज्ञान और कोर्टरूम रणनीति के बीच सेतु।",
  "VERIFY. AUTHENTICATE.": "सत्यापित करें। प्रमाणित करें।",
  "Document Examination": "दस्तावेज़ जांच",
  "Handwriting authentication, forgery detection, metadata inspection, and tamper checks — scientifically verified and court-ready.": "हस्तलेखन प्रमाणीकरण, जालसाज़ी का पता लगाना, मेटाडेटा निरीक्षण, और छेड़छाड़ जांच — वैज्ञानिक रूप से सत्यापित और कोर्ट-तैयार।",
  "DETECT. RESPOND. RECOVER.": "पहचानें। जवाब दें। रिकवर करें।",
  "Cyber Investigation": "साइबर जांच",
  "Malware analysis, threat intelligence, and data breach investigation — identifying, containing, and tracing cyber attacks back to their source.": "मैलवेयर विश्लेषण, थ्रेट इंटेलिजेंस, और डेटा ब्रीच जांच — साइबर हमलों की पहचान, नियंत्रण, और स्रोत तक ट्रेसिंग।",
  "ISO Certifications": "ISO प्रमाणन",
  "Service Verticals": "सेवा क्षेत्र",
  "Client Categories": "ग्राहक श्रेणियां",
  "Court-Admissible": "कोर्ट-स्वीकार्य",
  "ISO 27001:2022 Certified": "ISO 27001:2022 प्रमाणित",
  "Royal Vault Approach": "रॉयल वॉल्ट दृष्टिकोण",
  "Data treated as high-value assets — hidden, isolated, and accessible only to verified authorities.": "डेटा को उच्च-मूल्य संपत्ति के रूप में माना जाता है — छिपा हुआ, अलग, और केवल सत्यापित प्राधिकारियों के लिए सुलभ।",
  "AIR-GAPPED.": "एयर-गैप्ड।",
  "Combining secrecy, layered control, and modern air-gapped systems to create environments where data is not just stored — it is protected with discipline and zero exposure.": "गोपनीयता, स्तरित नियंत्रण, और आधुनिक एयर-गैप्ड सिस्टम को मिलाकर ऐसे वातावरण बनाना जहां डेटा को केवल संग्रहीत ही नहीं किया जाता — बल्कि अनुशासन और शून्य जोखिम के साथ सुरक्षित किया जाता है।",
  "Isolated air-gapped environments with no internet connectivity": "इंटरनेट कनेक्टिविटी के बिना अलग एयर-गैप्ड वातावरण",
  "Strong encryption protocols for data at rest": "स्थिर डेटा के लिए मजबूत एन्क्रिप्शन प्रोटोकॉल",
  "Role-based and device-based access with multi-layer authentication": "बहु-स्तरीय प्रमाणीकरण के साथ भूमिका-आधारित और डिवाइस-आधारित पहुंच",
  "Safe offline transfer via encrypted drives and controlled ports": "एन्क्रिप्टेड ड्राइव और नियंत्रित पोर्ट के माध्यम से सुरक्षित ऑफ़लाइन स्थानांतरण",
  "Full chain of custody — admissible and traceable in court": "पूर्ण चेन ऑफ कस्टडी — कोर्ट में स्वीकार्य और ट्रेस करने योग्य",
  "Aligned with DPDP Act 2023 and Section 63(4)(c) compliance": "DPDP अधिनियम 2023 और धारा 63(4)(c) अनुपालन के अनुरूप",
  "UNCOVER WHAT": "वह उजागर करें जो",
  "OTHERS MISS.": "दूसरे चूक जाते हैं।",
  "Beyond traditional audits — identifying fraud, financial irregularities, and hidden risks using investigative expertise and advanced analytics across 10+ targeted industries.": "पारंपरिक ऑडिट से आगे — 10+ लक्षित उद्योगों में जांच विशेषज्ञता और उन्नत विश्लेषण का उपयोग करके धोखाधड़ी, वित्तीय अनियमितताओं, और छिपे जोखिमों की पहचान करना।",
  "Fraud detection and financial irregularity identification": "धोखाधड़ी का पता लगाना और वित्तीय अनियमितता की पहचान",
  "Advanced analytics to trace discrepancies and hidden risks": "विसंगतियों और छिपे जोखिमों का पता लगाने के लिए उन्नत विश्लेषण",
  "Banking, Manufacturing, Real Estate, Healthcare & E-commerce": "बैंकिंग, विनिर्माण, रियल एस्टेट, स्वास्थ्य सेवा और ई-कॉमर्स",
  "Government & PSU projects, NGOs, Insurance companies": "सरकारी और PSU परियोजनाएं, NGO, बीमा कंपनियां",
  "Court-admissible, litigation-ready documentation": "कोर्ट-स्वीकार्य, मुकदमेबाज़ी-तैयार दस्तावेज़ीकरण",
  "10+ Targeted Industries": "10+ लक्षित उद्योग",
  "Banking, fintech, healthcare, real estate, NGOs, government PSU projects, and more.": "बैंकिंग, फिनटेक, स्वास्थ्य सेवा, रियल एस्टेट, NGO, सरकारी PSU परियोजनाएं, और अधिक।",
  "Multi-Platform Forensics": "मल्टी-प्लेटफ़ॉर्म फॉरेंसिक्स",
  "Computers, mobiles, cloud, CCTV, audio — every digital surface covered with evidence integrity guaranteed.": "कंप्यूटर, मोबाइल, क्लाउड, CCTV, ऑडियो — सबूत की अखंडता की गारंटी के साथ हर डिजिटल सतह कवर।",
  "EVIDENCE.": "सबूत।",
  "End-to-end investigations for law enforcement and corporate clients — evidence acquisition, analysis, and expert reporting with proper chain of custody.": "कानून प्रवर्तन और कॉर्पोरेट ग्राहकों के लिए एंड-टू-एंड जांच — उचित चेन ऑफ कस्टडी के साथ सबूत अधिग्रहण, विश्लेषण, और विशेषज्ञ रिपोर्टिंग।",
  "Computer Forensics — desktops, laptops, servers": "कंप्यूटर फॉरेंसिक्स — डेस्कटॉप, लैपटॉप, सर्वर",
  "Mobile Device Forensics — smartphones, SIM cards, WhatsApp, call logs": "मोबाइल डिवाइस फॉरेंसिक्स — स्मार्टफ़ोन, सिम कार्ड, WhatsApp, कॉल लॉग",
  "Email & Communication Forensics — phishing detection, deleted recovery": "ईमेल और संचार फॉरेंसिक्स — फ़िशिंग का पता लगाना, हटाई गई फ़ाइलों की रिकवरी",
  "Cloud Forensics — Google Drive, AWS, OneDrive": "क्लाउड फॉरेंसिक्स — Google Drive, AWS, OneDrive",
  "CCTV & Video Forensics — enhancement and authentication": "CCTV और वीडियो फॉरेंसिक्स — एन्हांसमेंट और प्रमाणीकरण",
  "Audio Forensics — voice analysis and tampering detection": "ऑडियो फॉरेंसिक्स — आवाज़ विश्लेषण और छेड़छाड़ का पता लगाना",
  "Expert Witness & Litigation Support": "विशेषज्ञ गवाह और मुकदमेबाज़ी सहायता",
  "FINANCIAL & FRAUD INVESTIGATION": "वित्तीय और धोखाधड़ी जांच",
  "TRACE THE MONEY.": "पैसे का पता लगाएं।",
  "EXPOSE THE FRAUD.": "धोखाधड़ी उजागर करें।",
  "Tracing digital evidence, reconstructing transactions, and identifying fraudulent intent — supporting organizations and authorities in cases of fraud, embezzlement, bribery, and corporate misconduct.": "डिजिटल सबूतों का पता लगाना, लेन-देन का पुनर्निर्माण करना, और धोखाधड़ी के इरादे की पहचान करना — धोखाधड़ी, गबन, रिश्वतखोरी, और कॉर्पोरेट कदाचार के मामलों में संगठनों और प्राधिकारियों का समर्थन करना।",
  "Transaction Trail Analysis — bank statements and digital ledgers": "लेन-देन ट्रेल विश्लेषण — बैंक स्टेटमेंट और डिजिटल लेजर",
  "Forensic Accounting — detecting manipulation and fund diversion": "फॉरेंसिक अकाउंटिंग — हेरफेर और फंड डायवर्जन का पता लगाना",
  "Data Manipulation Detection — altered or fabricated records": "डेटा हेरफेर का पता लगाना — बदले या गढ़े गए रिकॉर्ड",
  "Benami & Shell Entity Investigation — hidden ownership tracing": "बेनामी और शेल इकाई जांच — छिपे स्वामित्व का पता लगाना",
  "Insider Fraud — system logs and access history analysis": "इनसाइडर धोखाधड़ी — सिस्टम लॉग और पहुंच इतिहास विश्लेषण",
  "Cryptocurrency tracing across banking and digital platforms": "बैंकिंग और डिजिटल प्लेटफ़ॉर्म पर क्रिप्टोकरेंसी ट्रेसिंग",
  "Financial Crime Specialists": "वित्तीय अपराध विशेषज्ञ",
  "Forensic accounting, cryptocurrency tracing, benami entities, transaction trail analysis.": "फॉरेंसिक अकाउंटिंग, क्रिप्टोकरेंसी ट्रेसिंग, बेनामी संस्थाएं, लेन-देन ट्रेल विश्लेषण।",
  "OSINT & Beyond": "OSINT और उससे आगे",
  "Professional intelligence combined with investigative services for accurate, confident decisions.": "सटीक, आत्मविश्वासपूर्ण निर्णयों के लिए जांच सेवाओं के साथ पेशेवर खुफिया जानकारी।",
  "INVESTIGATIONS & INTELLIGENCE": "जांच और इंटेलिजेंस",
  "VERIFY.": "सत्यापित करें।",
  "Helping businesses and individuals verify information, identify risks, and make informed decisions — accurate, confidential, and built for security and compliance.": "व्यवसायों और व्यक्तियों को जानकारी सत्यापित करने, जोखिमों की पहचान करने, और सूचित निर्णय लेने में मदद करना — सटीक, गोपनीय, और सुरक्षा व अनुपालन के लिए निर्मित।",
  "Background Verification — identity, employment, education, criminal records": "पृष्ठभूमि सत्यापन — पहचान, रोज़गार, शिक्षा, आपराधिक रिकॉर्ड",
  "Corporate & Private Detective Services — misconduct, asset tracing, surveillance": "कॉर्पोरेट और निजी जासूसी सेवाएं — कदाचार, संपत्ति का पता लगाना, निगरानी",
  "Litigation Support — fact-finding, document review, case strategy": "मुकदमेबाज़ी सहायता — तथ्य-खोज, दस्तावेज़ समीक्षा, केस रणनीति",
  "Due Diligence — financial integrity, corporate history, reputation": "ड्यू डिलिजेंस — वित्तीय अखंडता, कॉर्पोरेट इतिहास, प्रतिष्ठा",
  "Open-Source Intelligence (OSINT) — social media, corporate records": "ओपन-सोर्स इंटेलिजेंस (OSINT) — सोशल मीडिया, कॉर्पोरेट रिकॉर्ड",
  "Business Intelligence & Risk Assessment": "बिज़नेस इंटेलिजेंस और जोखिम मूल्यांकन",
  "EVIDENCE TO": "सबूत से",
  "COURTROOM.": "कोर्टरूम तक।",
  "Strategic legal consultation backed by forensic insights — bridging the gap between technical evidence and legal strategy, ensuring every case is compliant and court-ready.": "फॉरेंसिक अंतर्दृष्टि द्वारा समर्थित रणनीतिक कानूनी परामर्श — तकनीकी सबूत और कानूनी रणनीति के बीच की खाई को पाटना, यह सुनिश्चित करना कि हर केस अनुपालित और कोर्ट-तैयार हो।",
  "Forensic-Legal Advisory — digital and physical evidence to admissible insights": "फॉरेंसिक-कानूनी सलाह — डिजिटल और भौतिक सबूतों से स्वीकार्य अंतर्दृष्टि",
  "Regulatory Compliance — DPDP Act 2023, IT Act 2000, financial regulations": "नियामक अनुपालन — DPDP अधिनियम 2023, IT अधिनियम 2000, वित्तीय नियम",
  "Expert Witness Services — courtroom testimony and technical explanations": "विशेषज्ञ गवाह सेवाएं — कोर्टरूम गवाही और तकनीकी स्पष्टीकरण",
  "Corporate Fraud & Risk Advisory": "कॉर्पोरेट धोखाधड़ी और जोखिम सलाह",
  "Litigation Support & Case Strategy": "मुकदमेबाज़ी सहायता और केस रणनीति",
  "Forensic-Legal Bridge": "फॉरेंसिक-कानूनी सेतु",
  "Technical evidence translated into legally admissible insights — every case structured and court-ready.": "तकनीकी सबूतों को कानूनी रूप से स्वीकार्य अंतर्दृष्टि में बदला गया — हर केस संरचित और कोर्ट-तैयार।",
  "Document Validation": "दस्तावेज़ सत्यापन",
  "Physical and digital document forensics — detecting forgery, tampering, and manipulation scientifically.": "भौतिक और डिजिटल दस्तावेज़ फॉरेंसिक्स — वैज्ञानिक रूप से जालसाज़ी, छेड़छाड़, और हेरफेर का पता लगाना।",
  "DOCUMENT EXAMINATION & VALIDATION": "दस्तावेज़ परीक्षण और सत्यापन",
  "AUTHENTIC OR": "असली या",
  "Comprehensive forensic examination of physical and digital documents — combining scientific analysis with advanced digital forensics to support legal proceedings and fraud investigations.": "भौतिक और डिजिटल दस्तावेज़ों की व्यापक फॉरेंसिक जांच — कानूनी कार्यवाही और धोखाधड़ी जांच का समर्थन करने के लिए वैज्ञानिक विश्लेषण को उन्नत डिजिटल फॉरेंसिक्स के साथ जोड़ना।",
  "Handwriting & Signature Authentication": "हस्तलेखन और हस्ताक्षर प्रमाणीकरण",
  "Forgery & Alteration Detection": "जालसाज़ी और परिवर्तन का पता लगाना",
  "Metadata & Digital Document Inspection — timestamps, backdating": "मेटाडेटा और डिजिटल दस्तावेज़ निरीक्षण — टाइमस्टैम्प, बैकडेटिंग",
  "Paper, Ink & Print Analysis": "कागज़, स्याही और प्रिंट विश्लेषण",
  "Tamper & Manipulation Checks": "छेड़छाड़ और हेरफेर जांच",
  "Evidentiary File Preparation — chain of custody compliance": "साक्ष्य फ़ाइल तैयारी — चेन ऑफ कस्टडी अनुपालन",
  "Full-Spectrum Cyber Response": "फुल-स्पेक्ट्रम साइबर रिस्पॉन्स",
  "WHO WE SERVE": "हम किसकी सेवा करते हैं",
  "OUR": "हमारे",
  "CLIENTS": "ग्राहक",
  "Government & Regulatory": "सरकार और नियामक",
  "Income Tax Department": "आयकर विभाग",
  "GST Department": "जीएसटी विभाग",
  "Enforcement Directorate": "प्रवर्तन निदेशालय",
  "CBI": "सीबीआई",
  "SEBI": "सेबी",
  "SFIO": "एसएफआईओ",
  "Law Enforcement & Legal": "कानून प्रवर्तन और कानूनी",
  "State Police & Cyber Crime Cells": "राज्य पुलिस और साइबर क्राइम सेल",
  "Economic Offences Wings": "आर्थिक अपराध शाखाएं",
  "Law Firms & Litigation Teams": "लॉ फ़र्म और मुकदमेबाज़ी टीमें",
  "Courts & Judicial Authorities": "अदालतें और न्यायिक प्राधिकारी",
  "Banking & Finance": "बैंकिंग और वित्त",
  "Public & Private Banks": "सार्वजनिक और निजी बैंक",
  "NBFCs": "एनबीएफसी",
  "Insurance Companies": "बीमा कंपनियां",
  "FinTech & Payment Providers": "फिनटेक और भुगतान प्रदाता",
  "Corporate & Business": "कॉर्पोरेट और व्यवसाय",
  "Large Corporates & MNCs": "बड़े कॉर्पोरेट और एमएनसी",
  "SMEs & Family Businesses": "एसएमई और पारिवारिक व्यवसाय",
  "Internal Audit Teams": "आंतरिक ऑडिट टीमें",
  "Compliance Departments": "अनुपालन विभाग",
  "Professional Firms": "पेशेवर फ़र्म",
  "CA Firms & Forensic Auditors": "सीए फ़र्म और फॉरेंसिक ऑडिटर",
  "Risk Advisory Firms": "जोखिम सलाहकार फ़र्म",
  "IBBI Insolvency Professionals": "IBBI दिवाला पेशेवर",
  "AWARENESS PROGRAMS": "जागरूकता कार्यक्रम",
  "EDUCATION IS THE": "शिक्षा ही है",
  "FIRST DEFENSE.": "पहली सुरक्षा।",
  "We extend our expertise beyond investigations into proactive crime prevention through structured awareness programs.": "हम अपनी विशेषज्ञता को जांच से परे संरचित जागरूकता कार्यक्रमों के माध्यम से सक्रिय अपराध रोकथाम तक विस्तारित करते हैं।",
  "Corporate Crime Awareness": "कॉर्पोरेट अपराध जागरूकता",
  "Equipping organizations to detect, prevent, and respond to modern financial and digital threats.": "संगठनों को आधुनिक वित्तीय और डिजिटल खतरों का पता लगाने, रोकने, और प्रतिक्रिया देने के लिए तैयार करना।",
  "Payment gateway manipulation & refund scams": "पेमेंट गेटवे हेरफेर और रिफंड घोटाले",
  "Business Email Compromise (BEC) attacks": "बिज़नेस ईमेल कॉम्प्रोमाइज़ (BEC) हमले",
  "CEO/CFO impersonation & social engineering": "CEO/CFO प्रतिरूपण और सोशल इंजीनियरिंग",
  "Insider data theft & confidential leaks": "इनसाइडर डेटा चोरी और गोपनीय लीक",
  "Legal & regulatory compliance obligations": "कानूनी और नियामक अनुपालन दायित्व",
  "POSH Act awareness & workplace ethics": "POSH अधिनियम जागरूकता और कार्यस्थल नैतिकता",
  "Crime Awareness for Students": "स्कूल अपराध जागरूकता",
  "Building safer schools by educating students, teachers, and parents about digital safety and protection.": "छात्रों, शिक्षकों, और माता-पिता को डिजिटल सुरक्षा और संरक्षण के बारे में शिक्षित करके सुरक्षित स्कूल बनाना।",
  "Cyberbullying, phishing & online scams": "साइबरबुलिंग, फ़िशिंग और ऑनलाइन घोटाले",
  "Social media safety & privacy protection": "सोशल मीडिया सुरक्षा और गोपनीयता संरक्षण",
  "Stranger danger & substance abuse awareness": "अजनबी खतरा और नशीली दवाओं के दुरुपयोग की जागरूकता",
  "Juvenile laws & student responsibilities": "किशोर कानून और छात्र ज़िम्मेदारियां",
  "Mental health & peer pressure management": "मानसिक स्वास्थ्य और सहकर्मी दबाव प्रबंधन",
  "POSH & safe school environment": "POSH और सुरक्षित स्कूल वातावरण",
  "READY TO PROTECT": "जो मायने रखता है उसे सुरक्षित करने के लिए",
  "WHAT MATTERS?": "तैयार हैं?",
  "Whether you need digital forensics, fraud investigation, or document validation — our certified team delivers court-admissible solutions when it matters most.": "चाहे आपको डिजिटल फॉरेंसिक्स, धोखाधड़ी जांच, या दस्तावेज़ सत्यापन की ज़रूरत हो — हमारी प्रमाणित टीम सबसे महत्वपूर्ण क्षणों में कोर्ट-स्वीकार्य समाधान प्रदान करती है।",
  "Fraud Investigation": "धोखाधड़ी जांच",
  "Investigations": "जांच",
  "Learn more →": "और जानें →",
  "ENCRYPTED.": "एन्क्रिप्टेड।",
  "COMPLIANT.": "अनुपालित।",
  "INTEGRITY.": "अखंडता।",
  "JUSTICE.": "न्याय।",
  "INVESTIGATE.": "जांच करें।",
  "MITIGATE.": "जोखिम कम करें।",
  "FORGED?": "जाली?",
  "WE KNOW.": "हम जानते हैं।",
  "ABOUT US": "हमारे बारे में",
  "Education, technology, and": "शिक्षा, प्रौद्योगिकी और",
  "justice": "न्याय",
  "— united.": "— एक साथ।",
  "Forfra Solutions Brochure": "Forfra Solutions ब्रोशर",
  "Who We Are?": "हम कौन हैं?",
  "Forfra Solutions is a multidisciplinary hub of forensic, cyber, and risk management experts with experience across Income Tax, GST, CBI, Police, ED, and other agencies.": "Forfra Solutions फॉरेंसिक, साइबर और जोखिम प्रबंधन विशेषज्ञों का एक बहु-विषयक केंद्र है, जिनके पास आयकर, GST, CBI, पुलिस, ED और अन्य एजेंसियों का अनुभव है।",
  "We deliver trusted solutions in digital forensics, fraud investigation, data security, and forensic education.": "हम डिजिटल फॉरेंसिक्स, धोखाधड़ी जांच, डेटा सुरक्षा और फॉरेंसिक शिक्षा में भरोसेमंद समाधान प्रदान करते हैं।",
  "At the crossroads of science and technology, Forfra Solutions redefines modern forensic practices — integrating advanced methodologies with innovative tools to accelerate investigations.": "विज्ञान और प्रौद्योगिकी के संगम पर, Forfra Solutions आधुनिक फॉरेंसिक प्रथाओं को नए सिरे से परिभाषित करता है — जांच को गति देने के लिए उन्नत पद्धतियों को नवीन उपकरणों के साथ जोड़कर।",
  "Credentials": "प्रमाण-पत्र",
  "Our ISO": "हमारे ISO",
  "Certifications": "प्रमाणन",
  "We are ISO 9001 certified, ensuring consistent quality, structured processes, and a customer-first approach.": "हम ISO 9001 प्रमाणित हैं, जो सुसंगत गुणवत्ता, संरचित प्रक्रियाओं और ग्राहक-प्रथम दृष्टिकोण को सुनिश्चित करता है।",
  "We are also ISO 27001 certified, guaranteeing the highest level of data security and risk management.": "हम ISO 27001 प्रमाणित भी हैं, जो डेटा सुरक्षा और जोखिम प्रबंधन के उच्चतम स्तर की गारंटी देता है।",
  "Our Promise": "हमारा वादा",
  "We deliver precise, ethical, and confidential forensic and digital solutions.": "हम सटीक, नैतिक और गोपनीय फॉरेंसिक व डिजिटल समाधान प्रदान करते हैं।",
  "Across classrooms, courtrooms, and fieldwork, we uphold integrity, transparency, and excellence.": "कक्षाओं, अदालतों और फील्डवर्क में, हम ईमानदारी, पारदर्शिता और उत्कृष्टता को बनाए रखते हैं।",
  "Our Mission": "हमारा मिशन",
  "At the intersection of science, education, and justice, Forfra Solutions empowers students, legal professionals, and law enforcement with expert-led forensic solutions.": "विज्ञान, शिक्षा और न्याय के संगम पर, Forfra Solutions विशेषज्ञ-नेतृत्व वाले फॉरेंसिक समाधानों के साथ छात्रों, कानूनी पेशेवरों और कानून प्रवर्तन को सशक्त बनाता है।",
  "Ready to work with": "काम करने के लिए तैयार हैं",
  "certified experts?": "प्रमाणित विशेषज्ञों के साथ?",
  "Back": "वापस",
  "View All Services": "सभी सेवाएँ देखें",
  "Awareness Program": "जागरूकता कार्यक्रम",
  "Corporate Crime": "कॉर्पोरेट अपराध",
  "In the digital era, one careless click or misplaced trust can cost a company millions. Our program is designed to protect organizations from fintech frauds, insider scams, cyber threats, and workplace misconduct through real-world education and proactive defence training.": "डिजिटल युग में, एक लापरवाह क्लिक या गलत जगह रखा गया भरोसा किसी कंपनी को करोड़ों का नुकसान पहुँचा सकता है। हमारा कार्यक्रम संगठनों को फिनटेक धोखाधड़ी, इनसाइडर घोटालों, साइबर खतरों और कार्यस्थल पर दुराचार से बचाने के लिए वास्तविक दुनिया की शिक्षा और सक्रिय सुरक्षा प्रशिक्षण के माध्यम से बनाया गया है।",
  "Delivered by certified forensic and cyber-risk experts, these sessions transform employees into your first line of defence — alert, informed, and legally aware.": "प्रमाणित फॉरेंसिक और साइबर-जोखिम विशेषज्ञों द्वारा संचालित ये सत्र कर्मचारियों को आपकी सुरक्षा की पहली पंक्ति में बदल देते हैं — सतर्क, जागरूक और कानूनी रूप से सजग।",
  "What You'll": "आप क्या",
  "Learn": "सीखेंगे",
  "Fintech & Corporate Frauds": "फिनटेक और कॉर्पोरेट धोखाधड़ी",
  "Payment gateway scams, fake invoicing, and money mule networks.": "पेमेंट गेटवे घोटाले, फ़र्ज़ी इनवॉइसिंग और मनी म्यूल नेटवर्क।",
  "Digital Exploitation": "डिजिटल शोषण",
  "Business Email Compromise (BEC), phishing, and impersonation attacks.": "बिज़नेस ईमेल कॉम्प्रोमाइज़ (BEC), फ़िशिंग और प्रतिरूपण हमले।",
  "Internal Threats": "आंतरिक खतरे",
  "Insider data theft, policy misuse, and weak compliance systems.": "इनसाइडर डेटा चोरी, नीतियों का दुरुपयोग और कमज़ोर अनुपालन प्रणालियाँ।",
  "Legal Frameworks": "कानूनी ढाँचे",
  "IT Act, IPC provisions, and internal reporting obligations.": "IT अधिनियम, IPC के प्रावधान और आंतरिक रिपोर्टिंग दायित्व।",
  "Workplace Safety": "कार्यस्थल सुरक्षा",
  "POSH Act guidelines, employee rights, and prevention mechanisms.": "POSH अधिनियम के दिशानिर्देश, कर्मचारियों के अधिकार और रोकथाम तंत्र।",
  "Key": "मुख्य",
  "Highlights": "विशेषताएँ",
  "Real case studies of corporate & fintech crimes in India": "भारत में कॉर्पोरेट और फिनटेक अपराधों के वास्तविक केस स्टडी",
  "How scams, phishing, and impersonation attacks unfold": "घोटाले, फ़िशिंग और प्रतिरूपण हमले कैसे घटित होते हैं",
  "Data security & insider threat prevention": "डेटा सुरक्षा और इनसाइडर खतरों की रोकथाम",
  "Legal awareness under IT & corporate laws": "IT और कॉर्पोरेट कानूनों के तहत कानूनी जागरूकता",
  "Workplace safety and POSH compliance": "कार्यस्थल सुरक्षा और POSH अनुपालन",
  "How We": "हम कैसे",
  "Deliver": "प्रदान करते हैं",
  "Every session is built around your organization's real risk profile — not a generic slideshow. We sit down with your leadership team first, understand where the exposure actually is, and design a session that leaves employees with practical habits, not just awareness.": "हर सत्र आपके संगठन के वास्तविक जोखिम प्रोफ़ाइल के आधार पर तैयार किया जाता है — कोई सामान्य स्लाइडशो नहीं। हम पहले आपकी लीडरशिप टीम के साथ बैठते हैं, समझते हैं कि जोखिम वास्तव में कहाँ है, और ऐसा सत्र डिज़ाइन करते हैं जो कर्मचारियों को केवल जागरूकता नहीं, बल्कि व्यावहारिक आदतें दे।",
  "Expert-Led Sessions": "विशेषज्ञ-नेतृत्व वाले सत्र",
  "Interactive sessions run by certified forensic and cyber-risk experts.": "प्रमाणित फॉरेंसिक और साइबर-जोखिम विशेषज्ञों द्वारा संचालित इंटरैक्टिव सत्र।",
  "Visual Case Breakdowns": "दृश्य केस विश्लेषण",
  "Real-world case walkthroughs and simulations that make risks tangible.": "वास्तविक केसों के वॉकथ्रू और सिमुलेशन जो जोखिमों को स्पष्ट रूप से समझाते हैं।",
  "Tailored Checklists": "अनुकूलित चेकलिस्ट",
  "Custom risk checklists and compliance recommendations for your team.": "आपकी टीम के लिए कस्टम जोखिम चेकलिस्ट और अनुपालन सिफ़ारिशें।",
  "Bring This Program": "यह कार्यक्रम लाएँ",
  "To Your Team": "अपनी टीम तक",
  "Reach out to schedule a session for your organization — tailored, practical, and delivered by certified experts.": "अपने संगठन के लिए सत्र निर्धारित करने हेतु संपर्क करें — अनुकूलित, व्यावहारिक और प्रमाणित विशेषज्ञों द्वारा संचालित।",
  "Crime Awareness": "अपराध जागरूकता",
  "for Students": "छात्रों के लिए",
  "We don't just teach about crimes — we teach how to stay safe, smart, and responsible. Our mission is to empower young minds with awareness, skills, and opportunities in forensic science and cyber safety.": "हम केवल अपराधों के बारे में नहीं सिखाते — हम सिखाते हैं कि सुरक्षित, समझदार और ज़िम्मेदार कैसे रहें। हमारा मिशन युवा मस्तिष्कों को फॉरेंसिक विज्ञान और साइबर सुरक्षा में जागरूकता, कौशल और अवसरों के साथ सशक्त बनाना है।",
  "Why Schools": "स्कूल क्यों",
  "Choose Us": "हमें चुनते हैं",
  "Practical & Interactive": "व्यावहारिक और इंटरैक्टिव",
  "Activities, games, and real-life examples that keep students engaged.": "गतिविधियाँ, खेल और वास्तविक जीवन के उदाहरण जो छात्रों को जुड़ाव में रखते हैं।",
  "Awareness With Safety": "सुरक्षा के साथ जागरूकता",
  "We educate without spreading fear or negativity.": "हम डर या नकारात्मकता फैलाए बिना शिक्षित करते हैं।",
  "Expert Trainers": "विशेषज्ञ प्रशिक्षक",
  "Sessions conducted by professionals who work with law enforcement agencies.": "कानून प्रवर्तन एजेंसियों के साथ काम करने वाले पेशेवरों द्वारा संचालित सत्र।",
  "Student Empowerment": "छात्र सशक्तिकरण",
  "Builds confidence, awareness, and future career interest.": "आत्मविश्वास, जागरूकता और भविष्य के करियर में रुचि विकसित करता है।",
  "Mission": "मिशन",
  "Teach juvenile laws and important helpline resources": "किशोर कानूनों और महत्वपूर्ण हेल्पलाइन संसाधनों की जानकारी देना",
  "Inspire students to become confident, vigilant, and proactive citizens": "छात्रों को आत्मविश्वासी, सतर्क और सक्रिय नागरिक बनने के लिए प्रेरित करना",
  "Encourage informed decision-making and standing against injustice": "सूझ-बूझ भरे निर्णय लेने और अन्याय के विरुद्ध खड़े होने को प्रोत्साहित करना",
  "Build a safer, smarter, and just society by spreading awareness today": "आज जागरूकता फैलाकर एक सुरक्षित, समझदार और न्यायपूर्ण समाज का निर्माण करना",
  "Counselling": "परामर्श",
  "Sessions": "सत्र",
  "Forensic Science & Career Opportunities": "फॉरेंसिक विज्ञान और करियर के अवसर",
  "Unlock the Secrets of Forensics": "फॉरेंसिक्स के रहस्यों को जानें",
  "Students discover how forensic science solves real-life mysteries — from digital forensics and biology to handwriting analysis, chemistry, and ballistics. Interactive case studies and hands-on activities like fingerprint collection make learning fun and engaging.": "छात्र जानते हैं कि फॉरेंसिक विज्ञान वास्तविक जीवन की पहेलियों को कैसे सुलझाता है — डिजिटल फॉरेंसिक्स और जीव विज्ञान से लेकर हस्तलेखन विश्लेषण, रसायन विज्ञान और बैलिस्टिक्स तक। इंटरैक्टिव केस स्टडी और फ़िंगरप्रिंट संग्रह जैसी व्यावहारिक गतिविधियाँ सीखने को मज़ेदार और आकर्षक बनाती हैं।",
  "Cyber Crime & Awareness": "साइबर अपराध और जागरूकता",
  "Stay Smart, Safe & Informed in the Digital World": "डिजिटल दुनिया में समझदार, सुरक्षित और जागरूक रहें",
  "Students are constantly connected through mobiles, social media, and online games. Our sessions help them recognize online fraud, cyberbullying, identity theft, deepfakes, and fake websites or emails — with legal insights and practical tips to navigate the online world responsibly.": "छात्र मोबाइल, सोशल मीडिया और ऑनलाइन गेम्स के ज़रिए लगातार जुड़े रहते हैं। हमारे सत्र उन्हें ऑनलाइन धोखाधड़ी, साइबरबुलिंग, पहचान की चोरी, डीपफेक और फ़र्ज़ी वेबसाइट या ईमेल पहचानने में मदद करते हैं — कानूनी जानकारी और व्यावहारिक सुझावों के साथ, ताकि वे ऑनलाइन दुनिया में ज़िम्मेदारी से आगे बढ़ सकें।",
  "Crime Scene Management": "क्राइम सीन प्रबंधन",
  "Building Safer Minds: Crime Awareness & Prevention": "सुरक्षित मस्तिष्कों का निर्माण: अपराध जागरूकता और रोकथाम",
  "Covers why people commit crimes, juvenile justice laws, suicide prevention, and the basics of crime scene investigation — helping students understand their legal rights, public responsibilities, and how to act wisely in critical situations.": "इसमें बताया जाता है कि लोग अपराध क्यों करते हैं, किशोर न्याय कानून, आत्महत्या की रोकथाम और अपराध स्थल जांच की बुनियादी बातें — ताकि छात्र अपने कानूनी अधिकार, सार्वजनिक ज़िम्मेदारियाँ और गंभीर परिस्थितियों में समझदारी से कैसे कार्य करें, यह समझ सकें।",
  "To Your School": "आपके स्कूल तक",
  "Reach out to schedule a session for your students — practical, safe, and delivered by certified experts.": "अपने छात्रों के लिए सत्र निर्धारित करने हेतु संपर्क करें — व्यावहारिक, सुरक्षित और प्रमाणित विशेषज्ञों द्वारा संचालित।",
  "Nearby Police Station": "नज़दीकी पुलिस स्टेशन",
  "Find the station closest to you.": "अपने सबसे नज़दीकी थाने को खोजें।",
  "A quick list of nearby stations with address and phone, so you know exactly where to go or who to call.": "नज़दीकी थानों की एक त्वरित सूची, पते और फ़ोन नंबर के साथ, ताकि आप जान सकें कि कहाँ जाना है या किसे कॉल करना है।",
  "Area": "क्षेत्र",
  "Near Me (sample list)": "मेरे पास (नमूना सूची)",
  "Model Town Police Station": "मॉडल टाउन पुलिस स्टेशन",
  "Model Town Rd, Sector 11": "मॉडल टाउन रोड, सेक्टर 11",
  "Civil Lines Police Station": "सिविल लाइन्स पुलिस स्टेशन",
  "Civil Lines, near District Court": "सिविल लाइन्स, जिला न्यायालय के पास",
  "Sarabha Nagar Police Station": "सराभा नगर पुलिस स्टेशन",
  "Sarabha Nagar Market Rd": "सराभा नगर मार्केट रोड",
  "Division No. 5 Police Station": "डिवीज़न नंबर 5 पुलिस स्टेशन",
  "Ghumar Mandi Chowk": "घुमार मंडी चौक",
  "1.2 km": "1.2 किमी",
  "2.4 km": "2.4 किमी",
  "3.1 km": "3.1 किमी",
  "4.6 km": "4.6 किमी",
  "📍 Sample listing shown for demo purposes — not live location data, no tracking involved. Contact your local station directly, or dial": "📍 यह नमूना सूची केवल डेमो के उद्देश्य से दिखाई गई है — यह लाइव लोकेशन डेटा नहीं है और कोई ट्रैकिंग नहीं होती। अपने स्थानीय थाने से सीधे संपर्क करें, या आपातकाल में",
  "for emergencies.": "डायल करें।",
  "Apply Now": "अभी आवेदन करें",
  "Contact Us": "संपर्क करें",
  "DETECT THE BREACH.": "ब्रीच का पता लगाएं।",
  "TRACE THE ATTACKER.": "हमलावर का पता लगाएं।",
  "When systems are compromised, speed and precision matter. Our cyber investigation team identifies malicious activity, maps the threat, and reconstructs how a breach happened — delivering clear, evidence-backed findings your organization and legal counsel can act on.": "जब सिस्टम से समझौता हो जाता है, तब गति और सटीकता मायने रखती है। हमारी साइबर जांच टीम दुर्भावनापूर्ण गतिविधि की पहचान करती है, खतरे का नक्शा बनाती है और पुनर्निर्माण करती है कि ब्रीच कैसे हुआ — ऐसे स्पष्ट, साक्ष्य-समर्थित निष्कर्ष देती है जिन पर आपका संगठन और कानूनी सलाहकार कार्रवाई कर सकें।",
  "Malware Analysis — static & dynamic analysis to identify malicious code and its behaviour": "मैलवेयर विश्लेषण — दुर्भावनापूर्ण कोड और उसके व्यवहार की पहचान के लिए स्थैतिक और गतिशील विश्लेषण",
  "Threat Intelligence — profiling attackers, tracking indicators of compromise (IOCs), and threat actor patterns": "थ्रेट इंटेलिजेंस — हमलावरों की प्रोफाइलिंग, इंडिकेटर्स ऑफ कॉम्प्रोमाइज़ (IOC) की ट्रैकिंग और थ्रेट एक्टर पैटर्न",
  "Data Breach Investigation — scope assessment, root-cause analysis, and impact reporting": "डेटा ब्रीच जांच — दायरे का आकलन, मूल-कारण विश्लेषण और प्रभाव रिपोर्टिंग",
  "Incident Response & Containment — isolating compromised systems and stopping active threats": "इंसिडेंट रिस्पॉन्स और कंटेनमेंट — प्रभावित सिस्टम को अलग करना और सक्रिय खतरों को रोकना",
  "Network & Log Forensics — tracing intrusion paths across servers, endpoints, and cloud systems": "नेटवर्क और लॉग फॉरेंसिक्स — सर्वर, एंडपॉइंट और क्लाउड सिस्टम में घुसपैठ के रास्तों का पता लगाना",
  "Post-Incident Reporting — compliance-ready reports for regulators, insurers, and leadership": "घटना-पश्चात रिपोर्टिंग — नियामकों, बीमाकर्ताओं और नेतृत्व के लिए अनुपालन-तैयार रिपोर्ट",
  "Malware analysis, threat intelligence, and data breach investigation — under one roof.": "मैलवेयर विश्लेषण, थ्रेट इंटेलिजेंस और डेटा ब्रीच जांच — एक ही छत के नीचे।",
  "Company": "कंपनी",
  "About Us": "हमारे बारे में",
  "Learn More": "और जानें",
  "Justice, Weighed Precisely": "न्याय, सटीकता से तौला हुआ",
  "Every case handled with balance & integrity": "हर केस संतुलन और ईमानदारी से संभाला जाता है",
  "Call Us": "हमें कॉल करें",
  "Call": "कॉल करें",
  "FIR Number": "FIR नंबर",
  "Submit your details through Whatsapp": "अपनी जानकारी WhatsApp के माध्यम से भेजें",
  "A criminal defence lawyer has been assigned to your case": "आपके केस के लिए एक आपराधिक बचाव वकील नियुक्त किया गया है",
  "A lawyer has been matched to your case": "आपके केस के लिए एक वकील मिला दिया गया है",
  "Evidence fades fast — ": "सबूत तेज़ी से मिट जाते हैं — ",
  "Tell us a bit about yourself — we'll reach out over WhatsApp.": "हमें अपने बारे में थोड़ा बताएं — हम WhatsApp पर आपसे संपर्क करेंगे।",
  "Role Applying For": "जिस पद के लिए आवेदन कर रहे हैं",
  "e.g. Cyber Investigator": "उदा. साइबर इन्वेस्टिगेटर",
  "Experience (optional)": "अनुभव (वैकल्पिक)",
  "e.g. 2 years / Fresher": "उदा. 2 वर्ष / फ्रेशर",
  "Message (optional)": "संदेश (वैकल्पिक)",
  "Anything you'd like us to know...": "कुछ भी जो आप हमें बताना चाहें...",
  "Resume / CV (optional)": "रिज़्यूमे / CV (वैकल्पिक)",
  "Tap to choose a PDF or Word file": "PDF या Word फ़ाइल चुनने के लिए टैप करें",
  "Send Application": "आवेदन भेजें",
  "Your details will open in WhatsApp. On the next screen, tap \"Share Resume\" to send your file too (or attach it manually if your device doesn't support direct sharing).": "आपकी जानकारी WhatsApp में खुलेगी। अगली स्क्रीन पर, अपनी फ़ाइल भी भेजने के लिए \"Share Resume\" पर टैप करें (या यदि आपका डिवाइस सीधे साझा करना सपोर्ट नहीं करता तो इसे मैन्युअली अटैच करें)।",
  "Your details will open in WhatsApp addressed to our team — please attach your resume/CV there before hitting send.": "आपकी जानकारी हमारी टीम को संबोधित WhatsApp में खुलेगी — कृपया भेजने से पहले वहाँ अपना रिज़्यूमे/CV अटैच करें।",
  "Thank You!": "धन्यवाद!",
  "Your details were sent to WhatsApp.": "आपकी जानकारी WhatsApp पर भेज दी गई है।",
  "Now share your resume below so our team has it too.": "अब नीचे अपना रिज़्यूमे साझा करें ताकि हमारी टीम के पास वह भी हो।",
  "Please attach your resume/CV in the chat and hit send — our team will get back to you soon.": "कृपया चैट में अपना रिज़्यूमे/CV अटैच करें और भेजें — हमारी टीम जल्द ही आपसे संपर्क करेगी।",
  "Shared! Share again?": "साझा हो गया! फिर से साझा करें?",
  "Share Resume via WhatsApp": "WhatsApp से रिज़्यूमे साझा करें",
  "Direct sharing isn't supported on this browser — please attach": "इस ब्राउज़र में सीधा साझा करना समर्थित नहीं है — कृपया अटैच करें",
  "manually in the WhatsApp chat.": "WhatsApp चैट में मैन्युअली।",
  "Close": "बंद करें",
};